### ISSUE TITLE
Audio

### ISSUE THREAD

**Issue by NO-ob** [tluck/Lenovo-T420-Clover#29]
Hi i'm wondering what you did to get audio working as I'm having trouble on my X220 opencore setup. I've tried every alcid from 0-30 in the alcid flag. I did test your efi just to see if it boots and the starting chime works so i assume theyre similar

**Comment by tluck** [comment]
well. i am not sure I did anything special. the DSDT has HDEF device. and the config.plist defines the alc-layout as 0E (14) and layout id (07). Note: the OC config is for 1600x900 (as I also inject a EDID and set DualLink to 1. see DeviceProperties section.

**Comment by bulog** [comment]
Maybe need SSDT-PNLF.aml for use to inject the audio device with OC bootloader(I saw this from one webpage), but I had no success for the audio.
All works with Clover

**Comment by tluck** [comment]
I think I see (maybe) where the problem is/was. I was setting alcid=14 as a bootarg. I JUST updated the config to the use DeviceProperties to inject layout-id 14 - which gets changed by AppleALC.kext to alc-layout-id. I removed the bootarg.

PNLF is for the LCD/Panel Display. Audio depends on HDEF device (which I explicitly define in the DSDT vs inject via Clover) this HDEF device defines the codec. and the AppleALC kext does the rest based on what the config.plist provides for the layout-id (0xE=14) 

I use the same DSDT and SSDT set for Clover and OC. I use the same (Lilu family) kexts for both too.  So if it the APCI files work in Clover then it will work in OC. 

your ioreg should look like this:
```
$ ioreg -l | grep layout

    | |   | |   "layout-id" = <07000000>
    | |   | |   "alc-layout-id" = <0e000000>
```
