### ISSUE TITLE
Windows 10 stuck on loading

### ISSUE THREAD

**Issue by tonyyang123** [tluck/Lenovo-T420-Clover#30]
v2020.09.13 is normal, v2020.12.10 is abnormal.

My laptop installed 11.2.3 by OpenCore-Legacy-Patcher and work fine, Windows 10 get stuck on loading, but boots fine from bootmenu, both systems are installed on the same ssd.

I added TG80211Family.kext to drive wifi and bluetooth, modify casr-active-config to EF0F0000, no other configuration modified

How can I fix it?

**Comment by juanpy0223** [comment]
> v2020.09.13 is normal, v2020.12.10 is abnormal.
> 
> My laptop installed 11.2.3 by OpenCore-Legacy-Patcher and work fine, Windows 10 get stuck on loading, but boots fine from bootmenu, both systems are installed on the same ssd.
> 
> I added TG80211Family.kext to drive wifi and bluetooth, modify casr-active-config to EF0F0000, no other configuration modified
> 
> How can I fix it?

Hello, this might be because opencore injects Modified Ssdt and dsdt to all system alike... In Dortania page they offer a work around, and it is to also install Refind boot loader; when you want to boot windows, you boot refind from opencore then choose windows...

In my case, I have Clover Bootloader on a pendrive, and use it to boot windows

**Comment by tluck** [comment]
i can't boot windows with OC either (ACPI files are not compatible?) . So i use clover to boot windows - which just uses native info. i dont see much advantage of OC on the T420.
